In [1]:
import pandas as pd

In [49]:
import json

# Open the file
outputs_list = []
with open('dump-metereologia-mensal.jsonl', 'r') as file:
    # Iterate over each line in the file
    for line in file:
        # Parse the JSON object from the line
        json_object = json.loads(line.strip())
        # Process the JSON object (for example, print it)
        df = pd.DataFrame.from_dict(json_object)

        
        for index,row in df.iterrows():
            if (len(row[0]["01"]) > 0):
                for month in ['01', '02', '03', '04', '05', '06', '07', '08', '09', '10', '11', '12']:
                    for data_point in row[0][month]:
                        # print()
                        data = {
                                'dtHrLeitura': data_point['dtHrLeitura'],
                                'pressaoAtm': data_point['pressaoAtm'],
                                'temperaturaExt': data_point['temperaturaExt'],
                                'umidadeExt': data_point['umidadeExt'],
                                'direcaoVento': data_point['direcaoVento'],
                                'velocidadeVento': data_point['velocidadeVento'],
                                'precipitacao': data_point['precipitacao'], 
                                'place': df.columns[0]
                            }
                        outputs_list.append(data)
                        
output_parsed = pd.DataFrame(outputs_list)

/tmp/ipykernel_7915/3833945563.py:15: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if (len(row[0]["01"]) > 0):
/tmp/ipykernel_7915/3833945563.py:17: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  for data_point in row[0][month]:
/tmp/ipykernel_7915/3833945563.py:15: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if (len(row[0]["01"]) > 0):
/tmp/ipykernel_7915/3833945563.py:17: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  for data_point in row[0][month]:
/tmp/ipykernel_7915/3833945563.py:15: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if (len(row[0]["01"]) > 0):
/tmp/ipykernel_7915/3833945563.py:15: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if (len(row[0]["01"]) > 0):
/tmp/ipykernel_7915/3833945563.py:15: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if (len(row[0]["01"]) > 0):
/tmp/ipykernel_7915/3833945563.py:17: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  for data_point in row[0][month]:
/tmp/ipykernel_7915/3833945563.py:15: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if (len(row[0]["01"]) > 0):
/tmp/ipykernel_7915/3833945563.py:17: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  for data_point in row[0][month]:

In [54]:
output_parsed[output_parsed["place"]=="EMIMB"]
# output_parsed

,dtHrLeitura,pressaoAtm,temperaturaExt,umidadeExt,direcaoVento,velocidadeVento,precipitacao,place
1417728,2017-01-01-10-00,1044.23,NaN,NaN,NaN,NaN,NaN,EMIMB
1417729,2017-01-01-10-05,1044.20,NaN,NaN,NaN,NaN,NaN,EMIMB
1417730,2017-01-01-10-10,1044.23,NaN,NaN,NaN,NaN,NaN,EMIMB
1417731,2017-01-01-10-15,1044.20,NaN,NaN,NaN,NaN,NaN,EMIMB
1417732,2017-01-01-10-20,1044.23,NaN,NaN,NaN,NaN,NaN,EMIMB
...,...,...,...,...,...,...,...,...
2120064,2024-06-20-17-39,1017.80,19.5,91.0,216.0,3.3,0.0,EMIMB
2120065,2024-06-20-17-44,1017.90,19.5,91.0,242.0,3.8,0.0,EMIMB
2120066,2024-06-20-17-49,1017.80,19.5,91.0,238.0,3.4,0.0,EMIMB
2120067,2024-06-20-17-54,1017.70,19.5,91.0,232.0,2.9,0.0,EMIMB
2120068,2024-06-20-17-59,1017.80,19.4,92.0,240.0,3.3,0.0,EMIMB

In [56]:
# substituindo pela informação do estado onde fica o maregrafo
maregrafos_dict = {
    "EMBEL": "PA",
    "EMSAN": "AP",
    "EMFOR": "CE",
    "EMSAL": "BA",
    "EMARC": "RJ",
    "EMIMB": "SC"
}

output_parsed['place'] = output_parsed['place'].replace(maregrafos_dict)

In [57]:
output_parsed

,dtHrLeitura,pressaoAtm,temperaturaExt,umidadeExt,direcaoVento,velocidadeVento,precipitacao,place
0,2021-01-08-15-38,996.3,26.4,87.0,305.0,2.7,0.4,PA
1,2021-01-08-15-43,996.5,26.5,87.0,311.0,2.9,0.0,PA
2,2021-01-08-15-48,996.9,26.6,86.0,301.0,2.9,0.0,PA
3,2021-01-08-15-53,997.4,26.8,85.0,325.0,2.3,0.0,PA
4,2021-01-08-15-58,997.9,26.8,85.0,87.0,2.0,1.0,PA
...,...,...,...,...,...,...,...,...
2120064,2024-06-20-17-39,1017.8,19.5,91.0,216.0,3.3,0.0,SC
2120065,2024-06-20-17-44,1017.9,19.5,91.0,242.0,3.8,0.0,SC
2120066,2024-06-20-17-49,1017.8,19.5,91.0,238.0,3.4,0.0,SC
2120067,2024-06-20-17-54,1017.7,19.5,91.0,232.0,2.9,0.0,SC
2120068,2024-06-20-17-59,1017.8,19.4,92.0,240.0,3.3,0.0,SC

In [65]:
# agora salvar um csv por variavel
for coluna in ['pressaoAtm', 'temperaturaExt', 'umidadeExt', 'direcaoVento', 'velocidadeVento', 'precipitacao']:
    subset_df = output_parsed[['dtHrLeitura','place',coluna]]
    subset_df.to_csv("metereologia-"+coluna+".csv",index=False)
    print(subset_df.head())

# output_parsed.to_csv("metereologia.csv", index=False)

        dtHrLeitura place  pressaoAtm
0  2021-01-08-15-38    PA       996.3
1  2021-01-08-15-43    PA       996.5
2  2021-01-08-15-48    PA       996.9
3  2021-01-08-15-53    PA       997.4
4  2021-01-08-15-58    PA       997.9
        dtHrLeitura place  temperaturaExt
0  2021-01-08-15-38    PA            26.4
1  2021-01-08-15-43    PA            26.5
2  2021-01-08-15-48    PA            26.6
3  2021-01-08-15-53    PA            26.8
4  2021-01-08-15-58    PA            26.8
        dtHrLeitura place  umidadeExt
0  2021-01-08-15-38    PA        87.0
1  2021-01-08-15-43    PA        87.0
2  2021-01-08-15-48    PA        86.0
3  2021-01-08-15-53    PA        85.0
4  2021-01-08-15-58    PA        85.0
        dtHrLeitura place  direcaoVento
0  2021-01-08-15-38    PA         305.0
1  2021-01-08-15-43    PA         311.0
2  2021-01-08-15-48    PA         301.0
3  2021-01-08-15-53    PA         325.0
4  2021-01-08-15-58    PA          87.0
        dtHrLeitura place  velocidadeVento
0  2021-01-08-15-38    PA              2.7
1  2021-01-08-15-43    PA              2.9
2  2021-01-08-15-48    PA              2.9
3  2021-01-08-15-53    PA              2.3
4  2021-01-08-15-58    PA              2.0
        dtHrLeitura place  precipitacao
0  2021-01-08-15-38    PA           0.4
1  2021-01-08-15-43    PA           0.0
2  2021-01-08-15-48    PA           0.0
3  2021-01-08-15-53    PA           0.0
4  2021-01-08-15-58    PA           1.0